[pytest]
testpaths = tests
python_files = test_*.py
addopts = -ra
filterwarnings =
	ignore:__array_wrap__ must accept context and return_scalar arguments:DeprecationWarning
	ignore:This process .* is multi-threaded, use of fork\(\) may lead to deadlocks in the child\.:DeprecationWarning:multiprocessing\.popen_fork
	ignore:Please use the new API settings to control TF32 behavior:UserWarning:torch
